import re


# Marker tags generated by CrisperWhisper verbatim mode
MARKER_FILLERS = {
    "um": r"\[UM\]",
    "uh": r"\[UH\]",
    "er": r"\[ER\]",
    "hmm": r"\[HMM\]",
    "ah": r"\[AH\]",
}

# Spoken filler words and discourse markers (matched with word boundaries)
SPOKEN_FILLERS = {
    "um": r"\bum+\b",
    "uh": r"\buh+\b",
    "er": r"\ber+\b",
    "hmm": r"\bhmm+\b",
    "ah": r"\bah+\b",
    "like": r"\blike\b",
    "you know": r"\byou\s+know\b",
    "basically": r"\bbasically\b",
    "actually": r"\bactually\b",
    "literally": r"\bliterally\b",
    "i mean": r"\bi\s+mean\b",
}


def detect_fillers(text):
    """
    Detect and count filler words and hesitation markers in transcription.
    Returns a dict with filler counts: {"um": 2, "like": 1, ...}
    """
    if not text or not text.strip():
        return {}

    filler_counts = {}

    # 1. First detect explicit marker tags from CrisperWhisper
    clean_text = text
    for filler_name, marker_pattern in MARKER_FILLERS.items():
        matches = re.findall(marker_pattern, text, re.IGNORECASE)
        if matches:
            filler_counts[filler_name] = filler_counts.get(filler_name, 0) + len(matches)
            # Remove markers from clean_text to prevent double counting
            clean_text = re.sub(marker_pattern, " ", clean_text, flags=re.IGNORECASE)

    # 2. Check for spoken natural fillers in the remaining text
    for filler_name, pattern in SPOKEN_FILLERS.items():
        matches = re.findall(pattern, clean_text, re.IGNORECASE)
        if matches:
            # If this filler was already counted via markers (e.g. um/uh), add the non-marker spoken instances
            filler_counts[filler_name] = filler_counts.get(filler_name, 0) + len(matches)

    # Filter out zeros
    return {k: v for k, v in filler_counts.items() if v > 0}